In [1]:
from utils.utils import *
import numpy as np
import networkx as nx

In [2]:
import numpy as np
# Create an empty 7 by 7 matrix
matrix = np.zeros((8, 8))

# Define the nodes for each sub complete graph
subgraph1 = [0, 1, 2]
subgraph2 = [3, 4, 5]
subgraph3 = [6,7]

# Set the values in the matrix for each sub complete graph
for i in subgraph1:
    for j in subgraph1:
        if i != j:
            matrix[i][j] = 1

for i in subgraph2:
    for j in subgraph2:
        if i != j:
            matrix[i][j] = 1

for i in subgraph3:
    for j in subgraph3:
        if i  != j:
            matrix[i][j] = 1



matrix = np.array([[0,1,1,0,0,0,0,0.],
                    [1,0,1,0,0,0,0,0.],
                    [1,1,0,0,0,0,0,0.],
                    [0,0,0,0,1,0,0,0.],
                    [0,0,0,1,0,1,0,0.],
                    [0,0,0,0,1,0,0,0.],
                    [0,0,0,0,0,0,0,1.],
                    [0,0,0,0,0,0,1,0.]])


G = nx.from_numpy_array(matrix)

local_expansion_kmeans(G,matrix,2,5)


HI1
[[-1.18058062e+00 -5.53421427e-01 -1.74606850e-01  3.71056071e-17
  -2.98474636e-17  1.15470054e+00]
 [-1.54012372e-01  1.86958429e+00 -8.28945507e-01 -6.44169337e-17
   1.05336281e-15 -7.41058302e-17]]


c:\Users\ASUS ROG\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
c:\Users\ASUS ROG\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: RuntimeWarning: Explicit initial center position passed: performing only one init in KMeans instead of n_init=10.
  super()._check_params_vs_input(X, default_n_init=10)
c:\Users\ASUS ROG\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
c:\Users\ASUS ROG\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_i

HI1
[[-1.18058062e+00 -5.53421427e-01 -1.74606850e-01  3.71056071e-17
  -2.98474636e-17  1.15470054e+00]
 [-1.54012372e-01  1.86958429e+00 -8.28945507e-01 -6.44169337e-17
   1.05336281e-15 -7.41058302e-17]
 [ 1.66859149e+00 -5.48782051e-01 -3.31903534e-01 -1.41820120e-16
   4.40515666e-16 -6.23416704e-17]]
HI1
[[-1.18058062e+00 -5.53421427e-01 -1.74606850e-01  3.71056071e-17
  -2.98474636e-17  1.15470054e+00]
 [-1.54012372e-01  1.86958429e+00 -8.28945507e-01 -6.44169337e-17
   1.05336281e-15 -7.41058302e-17]
 [ 1.66859149e+00 -5.48782051e-01 -3.31903534e-01 -1.41820120e-16
   4.40515666e-16 -6.23416704e-17]
 [ 1.79285625e-01  4.44122045e-01  1.00828656e+00 -9.99873506e-01
   1.59050841e-02  2.90929133e-16]]
HI1
[[-1.18058062e+00 -5.53421427e-01 -1.74606850e-01  3.71056071e-17
  -2.98474636e-17  1.15470054e+00]
 [-1.54012372e-01  1.86958429e+00 -8.28945507e-01 -6.44169337e-17
   1.05336281e-15 -7.41058302e-17]
 [ 1.66859149e+00 -5.48782051e-01 -3.31903534e-01 -1.41820120e-16
   4.405156

c:\Users\ASUS ROG\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
c:\Users\ASUS ROG\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: RuntimeWarning: Explicit initial center position passed: performing only one init in KMeans instead of n_init=10.
  super()._check_params_vs_input(X, default_n_init=10)
c:\Users\ASUS ROG\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


([[0, 1, 2], [3, 4, 5, 6, 7]], 0.5, 2)

In [3]:
fitness_function( a , [0,2])

Kin : 1
Kout : 3
Total : 4


4.348369522101714

In [22]:
np.sum(np.where(a != 0 , 1 , 0))/2

4.0

In [10]:
(77+14-2*32)**.5

5.196152422706632

In [8]:
s= similarity_matrix(a)

d=distance_matrix(s)

s,d

(array([[ 14,  32,  50],
        [ 32,  77, 122],
        [ 50, 122, 194]]),
 array([[ 0.        ,  5.19615242, 10.39230485],
        [ 5.19615242,  0.        ,  5.19615242],
        [10.39230485,  5.19615242,  0.        ]]))

In [17]:
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

def kmeans_clustering(X: np.ndarray, K: int, initial_seeds: list) -> np.ndarray:
    """
    This function takes a matrix X and the number of clusters K and returns the cluster indices.
    """
    kmeans = KMeans(n_clusters=K, random_state=0, init=initial_seeds).fit(X)
    return kmeans.labels_

In [8]:
D

array([[0.        , 1.41421356, 1.41421356, 1.73205081, 2.        ,
        1.73205081, 1.73205081, 1.73205081],
       [1.41421356, 0.        , 1.41421356, 1.73205081, 2.        ,
        1.73205081, 1.73205081, 1.73205081],
       [1.41421356, 1.41421356, 0.        , 1.73205081, 2.        ,
        1.73205081, 1.73205081, 1.73205081],
       [1.73205081, 1.73205081, 1.73205081, 0.        , 1.73205081,
        0.        , 1.41421356, 1.41421356],
       [2.        , 2.        , 2.        , 1.73205081, 0.        ,
        1.73205081, 1.73205081, 1.73205081],
       [1.73205081, 1.73205081, 1.73205081, 0.        , 1.73205081,
        0.        , 1.41421356, 1.41421356],
       [1.73205081, 1.73205081, 1.73205081, 1.41421356, 1.73205081,
        1.41421356, 0.        , 1.41421356],
       [1.73205081, 1.73205081, 1.73205081, 1.41421356, 1.73205081,
        1.41421356, 1.41421356, 0.        ]])

In [21]:

seeds_index = [0, 3, 4]



kmeans_clustering(D, 3, D[seeds_index])

c:\Users\ASUS ROG\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
c:\Users\ASUS ROG\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: RuntimeWarning: Explicit initial center position passed: performing only one init in KMeans instead of n_init=10.
  super()._check_params_vs_input(X, default_n_init=10)
c:\Users\ASUS ROG\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


array([0, 0, 0, 1, 2, 1, 1, 1])